---
title: "Wordle"
author: "Jim Pleuss and Dusty Turner"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
library(shinyjs)
source("wordle_functions.R")
reset()  
prep_words()
get_words() 
```

Inputs {.sidebar}
-------------------------------

Submit blank word and color scheme for initial word list

```{r echo=FALSE}


textInput(inputId = "word", label = "Add Word (ex. cares)")
textInput(inputId = "scheme", label = "Color Scheme (ex. bbgyb)")

actionButton("execute", "Submit")

```


sum_pos_props = sum of all the probabilities that the letter will appear in its particular position in the subset of feasible words

sum_prop_words = sum of all the probabilities that the letters will appear anywhere in the subset of feasible words.

repeat_ltrs = number of letters repeated in the word. Better to use 0 early on.

Rerun it for subsequent attempts. If you need to start over, just close and reopen it.


outputs
-------------------------------

```{r echo=FALSE}
table_data <- eventReactive(input$execute,  run_attempt(letters_attempt = input$word, colors_attempt = input$scheme))
# table_data <- eventReactive(input$initial, get_words())

# renderTable(initial_table())
renderTable(table_data())

```




<!-- ```{r echo=FALSE} -->

<!-- shinyApp( -->
<!--   ui = basicPage( -->
<!--     numericInput("num", label = "Make changes", value = 1), -->
<!--     submitButton("Update View", icon("refresh")), -->
<!--     helpText("When you click the button above, you should see", -->
<!--              "the output below update to reflect the value you", -->
<!--              "entered at the top:"), -->
<!--     verbatimTextOutput("value") -->
<!--   ), -->
<!--   server = function(input, output) { -->

<!--     # submit buttons do not have a value of their own, -->
<!--     # they control when the app accesses values of other widgets. -->
<!--     # input$num is the value of the number widget. -->
<!--     output$value <- renderPrint({ input$num }) -->
<!--   } -->
<!-- ) -->
<!-- ``` -->

